# Netlify configuration for Vite + React + TypeScript project
[build]
  command = "npm run build"
  publish = "dist"

# Prerender.io integration with token-based authentication
[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/https://perfume-ambassador.com/:splat"
  status = 200
  force = false
  headers = {X-Prerender-Token = "V85u5WS8kbxdXKCF5KuR"}
  conditions = {User-Agent = ["Googlebot", "Bingbot", "Yandex", "DuckDuckBot", "Baiduspider", "facebookexternalhit", "twitterbot", "rogerbot", "linkedinbot", "embedly", "quora link preview", "showyoubot", "outbrain", "pinterest", "slackbot", "vkShare", "W3C_Validator"]}

# SPA routing - fallback for regular users
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200